config/routes.rb
Rails.application.routes.draw do
  get 'response/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "requests#new"
  resources :requests
  devise_for :admins, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :admins do
    get 'sign_in', to: 'devise/sessions#new'
  end
  get 'admin/dashboard', :to => 'admin#dashboard'
end

app/models/admin.rb
class Admin < ApplicationRecord

  devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 12

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :rating, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def dashboard
    @requests = Request.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_admin!, :only => [:update, :edit]
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show

  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @admins = Admin.all

    respond_to do |format|
      if @request.save
        RequestMailer.with(request: @request).welcome_email.deliver_later

        if @request.email != ""
          @admins.each do |a|
            RequestMailer.with(request: @request, admin: a).new_request_email.deliver_late
          end
          format.html { redirect_to root_path, notice: 'Спасибо мы обязательно с вами свяжемся!' }
        else
          format.html { redirect_to root_path, notice: 'Спасибо за ваш отзыв!' }
        end
        #format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        #format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update

    respond_to do |format|
      if @request.update(request_params)
        RequestMailer.with(request: @request).response_email.deliver_later
        format.html { redirect_to admin_dashboard_path, notice: 'Отличная работа!' }
      else
        format.html { redirect_to admin_dashboard_path }
        #format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit!
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/response_helper.rb
module ResponseHelper
end

app/views/admin/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-sm-8 col-xs-12 offset-lg-3 offset-md-2 offset-sm-2 mt-5">
      <h1>Панель управления</h1>
      <p><%= link_to "Выйти", destroy_admin_session_path, method: :delete %></p>
      <hr>
      <% @requests.each do |t| %>
        <% if !t.email.blank? %>
        <div class="cell">
          <div class="request"><%= t.description %><%= link_to 'Ответить', edit_request_path(t), style: "float:right" %></div>
          <hr>
        </div>
        <% else %>
          <div class="cell">
            <div class="request"><%= t.description %></div>
            <hr>
          </div>
       <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for @request do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Ваше имя:" %>
    <%= f.input :email, label: "Email" %>
    <%= f.input :description, label: "Вопрос или отзыв:" %>
    <%= f.input :rating, label: "Оцените нас:", collection: 1..5, selected: 5 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Отправить", class: "btn btn-primary mb-5" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-sm-8 col-xs-12 offset-lg-3 offset-md-2 offset-sm-2 mt-5">
      <h1>Ответить на сообщение</h1>
      <%= simple_form_for @request do |f| %>
        <%= f.error_notification %>
        <p>Вопрос пользователя:</p>
        <p><%= @request.description %></p>
        <div class="form-inputs">
          <%= f.input :response, label: "Текст ответа" %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Отправить", class: "btn btn-primary mb-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-sm-8 col-xs-12 offset-lg-3 offset-md-2 offset-sm-2 mt-5">
      <h1>Новое обращение</h1>
      <p class="mt-5">У нас Вы можете оставить анонимный отзыв о нашем сервисе или задать вопрос. Мы обязательно свяжемся с Вами, ведь нам важен каждый!</p>
      <%= render 'form', request: @request %>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>